frases = [
    "El único modo de hacer un gran trabajo es amar lo que haces.",
    "El futuro pertenece a quienes creen en la belleza de sus sueños.",
    "La vida es 10% lo que te sucede y 90% cómo reaccionas ante ello.",
    "Nunca es demasiado tarde para ser lo que podrías haber sido.",
    "No cuentes los días, haz que los días cuenten.",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
    "Lo único imposible es aquello que no intentas.",
    "Cree en ti misma y todo será posible.",
    "No dejes que lo que no puedes hacer interfiera con lo que sí puedes hacer.",
    "Haz hoy lo que otros no quieren, haz mañana lo que otros no pueden.",
    "El único límite para nuestra realización de mañana son nuestras dudas de hoy.",
    "La vida comienza donde termina tu zona de confort.",
    "Persigue lo que te hace sentir vivo.",
    "El que no arriesga no gana.",
    "Si puedes soñarlo, puedes lograrlo.",
    "La clave del éxito es empezar antes de estar listo.",
    "El dolor que sientes hoy será la fuerza que tendrás mañana.",
    "Haz lo que puedas, con lo que tienes, donde estés.",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
    "No te rindas, cada día es una nueva oportunidad.",
    "La vida no se mide por las veces que respiras, sino por los momentos que te dejan sin aliento.",
    "Lo que no te mata, te hace más fuerte.",
    "La vida es como montar en bicicleta. Para mantener el equilibrio, debes seguir adelante.",
    "La diferencia entre lo posible y lo imposible radica en la voluntad humana.",
    "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.",
    "Los sueños no tienen fecha de caducidad.",
    "El primer paso es el más difícil, pero es el que te acerca a tu objetivo.",
    "Nunca te detengas. La victoria podría estar más cerca de lo que piensas.",
    "Lo importante no es lo que logras, sino lo que superas.",
    "El fracaso es solo la oportunidad de comenzar de nuevo con más inteligencia.",
    "Las oportunidades no ocurren, las creas.",
    "Si no luchas por lo que quieres, no te quejes por lo que pierdes.",
    "No importa lo lento que vayas, siempre y cuando no te detengas.",
    "Cada paso que des te acerca más a tus sueños.",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
    "La vida no espera, así que no dejes pasar las oportunidades.",
    "No importa cuántas veces caigas, lo importante es levantarte siempre.",
    "Cada día es una nueva oportunidad para ser la mejor versión de ti misma.",
    "El miedo es solo un obstáculo, la valentía es seguir adelante a pesar de él.",
    "Tu único límite es el que tú misma te pongas.",
    "Las personas que tienen éxito no son las que nunca fallan, sino las que nunca se rinden.",
    "Cree en ti misma y estarás a un paso más cerca de lo que deseas.",
    "Lo que haces hoy puede mejorar todos tus mañanas.",
    "El único fracaso verdadero es no intentarlo.",
    "No tengas miedo de ser diferente, ten miedo de ser igual que los demás.",
    "A veces, lo único que necesitas es un nuevo comienzo.",
    "La vida es corta, pero cada paso cuenta.",
    "Sigue tus sueños, ellos conocen el camino.",
    "El único modo de hacer un gran trabajo es amar lo que haces.",
    "Nunca dejes que alguien te diga que no puedes lograr algo.",
    "No te detengas hasta estar orgullosa de ti misma.",
    "Live and Learn.",
    "Gente como vos hace la diferencia.",
    "No hay mal que por bien no venga.",
    "Cría cuervos y te arrancarán los ojos.",
    "Dios los cría y el viento los amontona.",
    "Más sabe el Diablo por viejo que por Diablo.",
    "El camino al infierno está pavimentado de buenas intenciones.",
    "Qué tiene que ver el culo con la sociedad de fomento.",
    "Hay que tener siempre encendidas las luces del circo de la vida.",
    "Usar el tiempo en tonterias es la sal de cada día.",
    "La única batalla que se pierde es la que no se lucha.",
    "Cada día es una nueva oportunidad para empezar de nuevo.",
    "El éxito llega cuando tus sueños son más grandes que tus excusas.",
    "No esperes a que las condiciones sean perfectas para empezar; empezar hace que las condiciones sean perfectas.",
    "La perseverancia es el camino hacia el éxito.",
    "Haz lo que amas y no trabajarás un solo día de tu vida.",
    "El poder de la imaginación nos hace infinitos.",
    "Aprende del ayer, vive el hoy, espera el mañana.",
    "La grandeza no se mide por lo que logras, sino por los obstáculos que superas.",
    "El único límite a tus logros está en tu mente.",
    "No puedes controlar todas las situaciones, pero sí cómo reaccionas ante ellas.",
    "Cree en el proceso, incluso cuando el camino se sienta incierto.",
    "La fuerza no proviene de ganar, sino de luchar ante la adversidad.",
    "Tienes el poder de escribir tu propia historia.",
    "Nunca subestimes el impacto de un pequeño paso en la dirección correcta.",
    "Cada problema es una oportunidad para crecer y aprender.",
    "Lo que haces hoy define tu mañana.",
    "El cambio comienza en el momento en que decides actuar.",
    "No compares tu capítulo uno con el capítulo veinte de alguien más.",
    "Haz que cada día cuente, porque nunca volverá.",
    "Cada pequeño paso cuenta hacia un gran cambio.",
    "El único límite está en la imaginación.",
    "Lo importante no es caer, sino levantarse con más fuerza.",
    "La perseverancia transforma metas en logros.",
    "Cada día trae nuevas oportunidades para crecer.",
    "El éxito es el resultado de la constancia y la pasión.",
    "Nada es imposible cuando se da el máximo esfuerzo.",
    "El aprendizaje es el mayor regalo de la vida.",
    "La clave para avanzar es empezar.",
    "Cada decisión es una oportunidad para mejorar.",
    "La creatividad no tiene límites.",
    "El camino hacia el éxito está lleno de lecciones valiosas.",
    "La paciencia y el esfuerzo siempre tienen recompensa.",
    "Nunca es tarde para aprender algo nuevo.",
    "La confianza en uno mismo abre todas las puertas.",
    "El cambio comienza con un pensamiento positivo.",
    "El esfuerzo de hoy construye los sueños de mañana.",
    "La felicidad se encuentra en el viaje, no solo en el destino.",
    "Cada día es una página en blanco para escribir una nueva historia.",
    "La actitud positiva puede cambiar cualquier situación.",
]
